name:                rosen
version:             0.1.0.0
github:              "githubuser/rosen"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rosen#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers >= 0.2
- mtl >= 2.2.2
- random >= 1.2.1.1

library:
  source-dirs: src

executables:
  rosen-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rosen

tests:
  rosen-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rosen
    - QuickCheck >= 2.9.0
    - HUnit >= 1.5
    - test-framework
    - test-framework-quickcheck2

